### ISSUE TITLE
Bug in `abs` defn

### ISSUE THREAD

**Issue by anngvu** [quoll/asami#13]
Hello, thanks for working on this cool project. I was trying to set up latest version `"2.3.3"` to play around with but got complaints about not finding symbol `abs` or something wrong with `asami.durable.tree` ns when loading the lib. Looking through the code to the best of my ability (as someone very new to Clojure), it seems that while `abs` is still being used [here]( https://github.com/quoll/asami/blob/main/src/asami/durable/tree.cljc#L275), it was removed in `"v2.3.2"` in [this commit](https://github.com/quoll/asami/commit/7b36aaf82fc58341b80f80a8bce715d96604d6e5#diff-92af8172bd6bc1c9e7b097a7e7e180f3bf4b8539bb20aeb91b51c468d43b18a1L235-L239), thereby causing the issue?

Using version `"2.3.1"`, I was able to load data just fine with some typical code based off the example.

**Comment by markus-wa** [comment]
@anngvu make sure you have Clojure 1.11 - I had an entry in `~/.clojure/deps.edn` that forced version 1.10

**Comment by anngvu** [comment]
@markus-wa Thanks, that did indeed allow using the latest version. Hopefully this helps anyone else as well.
